### ISSUE TITLE
Final Capstone Kanban Board Setup

### ISSUE THREAD

**Issue by MrBrN197** [MrBrN197/book-a-book#19]
Github Project [Link](https://github.com/MrBrN197/FinalCapstoneBackend/projects/1)

## We are three people working on this project
@MrBrN197 
@Gambit142 
@2bleO 

## Kanban board screenshots
![image](https://user-images.githubusercontent.com/18730106/154516948-4ced0ebe-3b8b-4dbf-85ad-48e0ede149d5.png)
![image](https://user-images.githubusercontent.com/18730106/154516812-f5f307a4-8183-49fb-98eb-39e2d29e066d.png)
![image](https://user-images.githubusercontent.com/18730106/154516821-83ecc70c-932a-4c5f-bb0e-71ef4e9d9faf.png)
![image](https://user-images.githubusercontent.com/18730106/154516836-972cf67f-c2cf-46ff-97a7-b00265fb767b.png)

**Comment by MuriloRoque** [comment]
Hi @MrBrN197, @2bleO, @Gambit142, 

Good job so far!
There are some issues that you still need to work on but you are almost there!

## Suggested changes

- [x] Please add a screenshot of your current kanban board to this issue's description, just like the [requirements](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md) say.

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the issue thread if something is not 100% clear.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by MuriloRoque** [comment]
Hi @MrBrN197, @2bleO, @Gambit142,

In my opinion, your project is complete!

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
